sonata_admin:
    title: 'Fundin.AI ADMIN'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
            - position: right                              # zone in the dashboard
              type: sonata.admin.block.admin_preview # block id
              settings:
                  code: admin.grant_request          # admin code - service id
                  icon: fas fa-magic                     # font awesome icon
                  limit: 10
                  text: Latest Grant Requests
                  filters: # filter values
                      edited: { value: 1 }
                      _sort_by: id
                      _sort_order: DESC
            - position: right                              # zone in the dashboard
              type: sonata.admin.block.admin_preview # block id
              settings:
                  code: admin.funding_request          # admin code - service id
                  icon: fas fa-magic                     # font awesome icon
                  limit: 10
                  text: Latest Tender Requests
                  filters: # filter values
                      edited: { value: 1 }
                      _sort_by: id
                      _sort_order: DESC
    security:
        handler: sonata.admin.security.handler.role

        role_admin: ROLE_ADMIN
        role_super_admin: ROLE_SUPER_ADMIN

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
