version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: ankane/pgvector:latest
    container_name: gpt-funding.database
    environment:
      POSTGRES_PASSWORD: VdmPepu9WQeu8tbQCzLamyr2
#      POSTGRES_DB: funding
      POSTGRES_USER: funding
    ports:
      - "5432:5432"
    volumes:
#      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
       - ./docker/db/gpt-funding/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

###> meilisearch/search-bundle ###
  meilisearch:
    image: getmeili/meilisearch:${MEILISEARCH_VERSION:-v1.0}
    ports:
      - "7700:7700"
    environment:
      # You should definitely change the master key in production
      MEILI_MASTER_KEY: sdfewknkjabdsljbuerblVasdetyhnbvcx
    volumes:
      - meilisearch_data:/meili_data
###< meilisearch/search-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###

###> meilisearch/search-bundle ###
  meilisearch_data:
###< meilisearch/search-bundle ###
